services:
  - type: web
    name: gatepass-django
    env: python
    plan: free
    buildCommand: cd Gatepass && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py create_superuser_if_not_exists --noinput
    startCommand: cd Gatepass && gunicorn hostel_gatepass.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: gatepass-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@hostel.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true

databases:
  - name: gatepass-db
    plan: free
    databaseName: gatepass
    user: gatepass_user

